In [35]:
#imports
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [36]:
dataset= pd.read_csv('Social_Network_Ads.csv')

In [37]:
dataset.head()

Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [38]:
#Matrix of features(X) nad dependent variable vector(y)
X= dataset.iloc[:,:-1].values
y= dataset.iloc[:,-1].values


In [39]:
#Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=0)

In [40]:
X_train

array([[    24,  19000],
       [    42, 149000],
       [    46,  96000],
       [    28,  59000],
       [    39,  96000],
       [    28,  89000],
       [    41,  72000],
       [    45,  26000],
       [    33,  69000],
       [    20,  82000],
       [    31,  74000],
       [    42,  80000],
       [    35,  72000],
       [    33, 149000],
       [    40,  71000],
       [    51, 146000],
       [    46,  79000],
       [    35,  75000],
       [    38,  51000],
       [    36,  75000],
       [    37,  78000],
       [    38,  61000],
       [    60, 108000],
       [    20,  82000],
       [    57,  74000],
       [    42,  65000],
       [    26,  80000],
       [    46, 117000],
       [    35,  61000],
       [    21,  68000],
       [    28,  44000],
       [    41,  87000],
       [    37,  33000],
       [    27,  90000],
       [    39,  42000],
       [    28, 123000],
       [    31, 118000],
       [    25,  87000],
       [    35,  71000],
       [    37,  70000],


In [41]:
y_train

array([0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0])

In [42]:
X_test

array([[    30,  87000],
       [    38,  50000],
       [    35,  75000],
       [    30,  79000],
       [    35,  50000],
       [    27,  20000],
       [    31,  15000],
       [    36, 144000],
       [    18,  68000],
       [    47,  43000],
       [    30,  49000],
       [    28,  55000],
       [    37,  55000],
       [    39,  77000],
       [    20,  86000],
       [    32, 117000],
       [    37,  77000],
       [    19,  85000],
       [    55, 130000],
       [    35,  22000],
       [    35,  47000],
       [    47, 144000],
       [    41,  51000],
       [    47, 105000],
       [    23,  28000],
       [    49, 141000],
       [    28,  87000],
       [    29,  80000],
       [    37,  62000],
       [    32,  86000],
       [    21,  88000],
       [    37,  79000],
       [    57,  60000],
       [    37,  53000],
       [    24,  58000],
       [    18,  52000],
       [    22,  81000],
       [    34,  43000],
       [    31,  34000],
       [    49,  36000],


In [43]:
# Feature Scaling 
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
X_train= sc.fit_transform(X_train)
X_test= sc.transform(X_test)

## Logistic Regression Model

In [44]:
from sklearn.linear_model import LogisticRegression
classifier= LogisticRegression()
classifier.fit(X_train,y_train)

LogisticRegression()

In [45]:
#predicition
y_pred= classifier.predict(X_test)

In [46]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[78  6]
 [11 37]]


0.8712121212121212

## KNN

In [47]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(X_train, y_train)


KNeighborsClassifier()

In [48]:
#predicting new result
y_pred= classifier.predict(X_test)

In [49]:
#accuracy
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[77  7]
 [ 6 42]]


0.9015151515151515

## SVM

In [50]:
from sklearn.svm import SVC
classifier= SVC(kernel='linear')
classifier.fit(X_train,y_train)

SVC(kernel='linear')

In [51]:
y_pred= classifier.predict(X_test)

In [52]:
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[79  5]
 [14 34]]


0.8560606060606061

## Kernel SVM


In [53]:
from sklearn.svm import SVC
classifier= SVC(kernel='rbf')
classifier.fit(X_train, y_train)

SVC()

In [54]:
y_pred= classifier.predict(X_test)

In [55]:
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[76  8]
 [ 4 44]]


0.9090909090909091

## Naive Bayes

In [56]:
from sklearn.naive_bayes import GaussianNB
classifier= GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [57]:
y_pred= classifier.predict(X_test)

In [58]:
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[79  5]
 [ 7 41]]


0.9090909090909091

## Decision Trees

In [59]:
from sklearn.tree import DecisionTreeClassifier
classifier= DecisionTreeClassifier(criterion='entropy')
classifier.fit(X_train,y_train)

DecisionTreeClassifier(criterion='entropy')

In [60]:
y_pred= classifier.predict(X_test)

In [61]:
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[74 10]
 [ 6 42]]


0.8787878787878788

## Random Forest 

In [62]:
from sklearn.ensemble import RandomForestClassifier
classifier= RandomForestClassifier(criterion='entropy')
classifier.fit(X_train,y_train)

RandomForestClassifier(criterion='entropy')

In [63]:
y_pred= classifier.predict(X_test)

In [64]:
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[78  6]
 [ 7 41]]


0.9015151515151515